#!/bin/sh

SCRIPT_DIR=`dirname $0`

if test -f $SCRIPT_DIR/../.config; then
  . $SCRIPT_DIR/../.config
else
  echo "ERROR: Missing .config.  Run the configuration tool first." 1>&2
  exit 1
fi

. $SCRIPT_DIR/pre-install || (echo "ERROR: Failed Sanity Checks" 1>&2 && exit 1)

. $SCRIPT_DIR/install-idm

. $SCRIPT_DIR/install-satellite

echo "All done!"

. $SCRIPT_DIR/post-install
