#!/bin/sh

# This script should only be run by root...
if [ "$(id -u)" != "0" ]; then
  echo "ERROR: You must run this as root" 1>&2
  exit 1
fi

# Update resolv.conf to remove IdM
grep --quiet 10.0.0.99 /etc/resolv.conf
if [ $? -eq 0 ]; then 
  cat /etc/resolv.conf | sed 's/nameserver 10.0.0.99//' > /etc/resolv.conf
fi

echo "All done!"
